name: Build Artifacts
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Publish image to ghcr.io"
        type: boolean
        default: true
        required: false
env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  PUSH: ${{ (github.event_name == 'workflow_dispatch' && inputs.publish_docker) || !startsWith(github.ref, 'refs/heads/dependabot') }}
  GITHUB_GROUP: ${{ github.repository_owner }}

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-opensearch-integration-tests
            file: integration-tests/docker/Dockerfile
            context: integration-tests
          - name: qubership-opensearch-tls-init
            file: tls-init/docker/Dockerfile
            context: tls-init
          - name: qubership-opensearch-operator
            file: Dockerfile
            context: .
          - name: qubership-opensearch-transfer
            file: docker-transfer/Dockerfile
            context: ""
          - name: qubership-opensearch-monitoring
            file: monitoring/docker/Dockerfile
            context: monitoring
          - name: qubership-opensearch-curator
            file: opensearch-curator/docker/backup-docker/Dockerfile
            context: opensearch-curator
          - name: qubership-opensearch-indices-cleaner
            file: opensearch-curator/opensearch_indices_cleaner/docker/Dockerfile
            context: opensearch-curator/opensearch_indices_cleaner
          - name: qubership-opensearch-dbaas-adapter
            file: opensearch-dbaas-adapter/docker/Dockerfile
            context: opensearch-dbaas-adapter
          - name: qubership-docker-opensearch
            file: docker-opensearch/docker/Dockerfile
            context: docker-opensearch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Prepare Group
        run: echo "GITHUB_GROUP=${GITHUB_GROUP,,}" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
        if: ${{ env.PUSH }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ env.PUSH }}
          tags: ghcr.io/${{ env.GITHUB_GROUP }}/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
